name: heritability
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - bcftools=1.9
  - pandoc=2.12
  - plink=1.90b6.12
  - bedtools=2.29.2
  - r
  # - r-tidyverse
  # - r-data.table
  # - r-boot
  # - r-lme4
  # - r-futile.logger
  # - r-knitr
  # - r-rmarkdown
  # - r-sommer