name: heritability
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - bcftools=1.9
  - pandoc=2.12
  - plink=1.90b6.12
  - bedtools=2.29.2
  - libiconv
  - r=3.6.0
  - r-tidyselect=1.1.0
  - r-tidyverse=1.3.0
  - r-devtools=2.0.2
  - r-data.table=1.12.2
  - r-DT=0.5
  - r-genetics=1.3.8.1.2
  - r-ggbeeswarm=0.6.0
  - r-ggnewscale=0.4.5
  - r-ggrepel=0.9.1
  - r-knitr=1.22
  - r-rmarkdown=1.12
  - r-plotly=4.9.0
  - r-RSpectra=0.16-0
  - r-sommer=4.0.4
  - r-coop=0.6-2
  - r-cowplot=0.9.1
  - r-boot